---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: thegeeklab/cc-arm
  commands:
  - /bin/bash ./build.sh
  environment:
    COMPILER_CC: arm-rpi-linux-gnueabihf-gcc -march=armv7-a -static-libstdc++
    COMPILER_CXX: arm-rpi-linux-gnueabihf-g++ -march=armv7-a -static-libstdc++
    NODE_VERSION: ${DRONE_TAG##v}

- name: checksum
  image: alpine
  commands:
  - apk add --no-cache coreutils
  - sha256sum -b dist/* > sha256sum.txt

- name: gpg-sign
  pull: always
  image: plugins/gpgsign:1
  settings:
    detach_sign: true
    files:
    - dist/*
    key:
      from_secret: gpgsign_key
    passphrase:
      from_secret: gpgsign_passphrase
  when:
    ref:
    - refs/tags/**

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: NOTE.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- linux-amd64

---
kind: signature
hmac: a9951719559f862af44d4ce947d9b7e77a4f5755ff8d8f66b62cec629eca23d9

...
