---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: centos:7
  commands:
  - /bin/bash ./build.sh
  environment:
    NODE_VERSION: 10.15.3

- name: publish-github
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "dist/*"
    - sha256sum.txt
  when:
    event:
    - tag
...
