---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: xoxys/cc-arm
  commands:
  - /bin/bash ./build.sh
  environment:
    COMPILER_CC: arm-rpi-linux-gnueabihf-gcc -march=armv7-a -static-libstdc++
    COMPILER_CXX: arm-rpi-linux-gnueabihf-gcc -march=armv7-a -static-libstdc++
    NODE_VERSION: "${DRONE_TAG##v}"

- name: publish-github
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "dist/*"

trigger:
  event:
  - tag

...
