---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: xoxys/cc-arm:linux-amd64
  commands:
  - /bin/bash ./build.sh
  environment:
    COMPILER_CC: arm-rpi-linux-gnueabihf-gcc -march=armv7-a -static-libstdc++
    COMPILER_CXX: arm-rpi-linux-gnueabihf-g++ -march=armv7-a -static-libstdc++
    NODE_VERSION: "${DRONE_TAG##v}"

- name: checksum
  pull: always
  image: alpine
  commands:
  - apk add --no-cache coreutils
  - "sha256sum -b dist/* > sha256sum.txt"

- name: gpg-sign
  pull: always
  image: plugins/gpgsign:1
  settings:
    detach_sign: true
    files:
    - "dist/*"
    key:
      from_secret: gpgsign_key
    passphrase:
      from_secret: gpgsign_passphrase

- name: publish-github
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "dist/*"
    - sha256sum.txt
    note: NOTE.md
    title: "${DRONE_TAG}"

trigger:
  event:
  - tag

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver: https://matrix.rknet.org
    password:
      from_secret: matrix_password
    roomid: MtidqQXWWAtQcByBhH:rknet.org
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

depends_on:
- linux-amd64

...
