---
kind: pipeline
name: build

platform:
  os: linux
  arch: arm

steps:
- name: build
  pull: always
  image: xoxys/rpmbuild-centos7
  commands:
  - /bin/bash ./build.sh
  environment:
    NODE_VERSION: 10.15.3

...
